name: Deployment Pipeline

on:
  push:
    branches:
      - main 

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH Key and SSH Agent
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.GCP_SSH_PRIVATE_KEY }}" | tr -d '\r' > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          eval $(ssh-agent -s)
          ssh-add ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.GCP_VM_IP }} >> ~/.ssh/known_hosts

      - name: Deploy to GCP
        run: |
          ssh -o StrictHostKeyChecking=no jkpresh@${{ secrets.GCP_VM_IP }} << 'EOF'
            cd hng12-stage2-fastapi-book-project
            git pull origin main
            source venv/bin/activate
            pip install -r requirements.txt
            systemctl restart fastapi
          EOF